name: Nightly Merge Dev_Test to New_QA_Test

on:
  schedule:
    - cron: '5 6 * * *' # Runs at 6:05 AM UTC, equivalent to 11:35 AM IST
  workflow_dispatch: # Allows manual triggering

jobs:
  merge-dev_test-to-new_qa_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Merge dev into qa
        run: |
          git checkout qa
          git merge origin/dev --no-edit
          git push origin qa

      - name: Notify on conflict
        if: failure()
        run: echo "Merge conflict detected. Please resolve manually."